all:
	gcc -o a a.c
	./a word input.txt
	./a word -d input.txt input1.txt
	./a word -n input.txt

c:
	gcc EXEC.c -o 2
	gcc -o 21 Q2_3.c
	./2 date input.txt
	./2 date -R input.txt
	./2 date -d 'yesterday' input.txt
	./2 date -t input.txt
	./2 date input2.txt
clear:
	rm a
	rm 2
	rm 21